ALTER TABLE agents ADD COLUMN IF NOT EXISTS soul_md TEXT DEFAULT NULL;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS identity_md TEXT DEFAULT NULL;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS identity JSONB DEFAULT NULL;
